# ??? ??? ????? ???? ????.
# ?? ?? ??
server:
  port: 8761

# ???????? ???? ????? ??? ???
# ??? ???????? ??? ???? ???? ??
spring:
  application:
    name: eureka_service


## client ?? ##
# ?? ??? ??? ????? ? client ??? ?????
# eureka ?????? ??? ? ?????? ??? ??
# ????? eureka ?????? ???? ???? ???? ??? ????.
# ?? ???? ???? true? ?? ????? client? ??? ?????? ???? ?? ??.
# ?? ????? ??(?????)? ? ??? ??? ??? ???? ???? ??? ??.
# ??? ?? ????? false? ?????.
# ????? ?? ????? ??? ??(?????)??? ????? ??? ???? ???? ??? ???? ????.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
